
-- SQL que crea estructura de sistema de medicion de temperaturas

DROP TABLE IF EXISTS TEMPERATURES;

CREATE TABLE TEMPERATURES (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  VALUE FLOAT(6) DEFAULT NULL,
  MONTH VARCHAR(255) NOT NULL,
  MONTH_OF_YEAR INT(2) NOT NULL,
  YEAR INT(4) NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BOOKINGS;

CREATE TABLE BOOKINGS (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(255) NOT NULL,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME NOT NULL,
	APARTMENT VARCHAR(255) NOT NULL,
	NUMBER_PEOPLE INT(10) NOT NULL,
	PETS BOOLEAN NOT NULL,
	PRIMARY KEY (ID)
);

