DROP TABLE USERS IF EXISTS;
DROP TABLE CARS IF EXISTS;
DROP TABLE CAR_REFERENCES IF EXISTS;


CREATE TABLE USERS(

USER_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(50),
PASSWORD VARCHAR(50),
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
PHONE_NUMBER VARCHAR(50),
ADDRESS VARCHAR(50));


CREATE TABLE CARS(

CAR_ID INT AUTO_INCREMENT PRIMARY KEY,
MODEL VARCHAR(30),
BRAND VARCHAR(30),
PRICE INT);

CREATE TABLE CAR_REFERENCES(
CAR_TOKEN INT REFERENCES CARS(CAR_ID),
USER_ID INT REFERENCES USERS(USER_ID),
PRIMARY KEY (CAR_TOKEN, USER_ID));



--INSERT INTO CARS (CAR_ID, MODEL, BRAND, PRICE) VALUES
--(1, 'polo', 'volkswagen', 10000),
--(2, 'pasat', 'volkswagen', 15000),
--(3, 'kompresor','mercedes', 30000),
--(4, 'Q3', 'audi', 35000),
--(5, 'serie 1', 'bmw', 30000);